# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IncLj_PLaDq0a2dNMwK2epMlJEqjyJs
"""

import os
import matplotlib.pyplot as plt

def read_words(file_path):
    word_count = {}  # hash table 初始化
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"找不到檔案：{file_path}")

    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            word = line.strip()
            if word:
                if word in word_count:
                    word_count[word] += 1
                else:
                    word_count[word] = 1
    return word_count

# 顯示統計資訊
def print_word_stats(word_count):
    print(f"不重複的英文字總共有：{len(word_count)} 個")
    print("\n每個英文字的出現次數：")
    for word, count in word_count.items():
        print(f"{word}: {count}")

# 繪製直方圖
def plot_histogram(word_count):
    sorted_items = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
    words = [item[0] for item in sorted_items]
    counts = [item[1] for item in sorted_items]

    plt.figure(figsize=(10, 6))
    plt.bar(words, counts, color='skyblue', edgecolor='black')
    plt.title("🍟 Word Frequency Histogram", fontsize=16)
    plt.xlabel("Words", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.xticks(rotation=45)
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.savefig("Figure_1.png")
    plt.show()

# 主程式入口
if __name__ == "__main__":
    file_path = "hw2_data.txt"
    word_count = read_words(file_path)
    print_word_stats(word_count)
    plot_histogram(word_count)

from google.colab import drive
drive.mount('/content/drive')