# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IncLj_PLaDq0a2dNMwK2epMlJEqjyJs
"""

import os
import matplotlib.pyplot as plt
import plotly.express as px


def read_words(file_path):
    word_count = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            word = line.strip()
            if word:
                if word in word_count:
                    word_count[word] += 1
                else:
                    word_count[word] = 1
    return word_count


def print_stats(word_count):
    total_unique = len(word_count)
    total_words = sum(word_count.values())
    most_common = max(word_count.items(), key=lambda x: x[1])

    print(f"✅ 不重複的英文字總共有：{total_unique} 個")
    print(f"🧮 單字總數（含重複）：{total_words}")
    print(f"🏆 最常出現的單字是：{most_common[0]}，共出現 {most_common[1]} 次\n")

    print("📊 每個單字的出現次數如下：")
    for word, count in word_count.items():
        print(f"{word}: {count}")


def plot_static_histogram(word_count):
    sorted_items = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
    words = [item[0] for item in sorted_items]
    counts = [item[1] for item in sorted_items]

    plt.figure(figsize=(10, 6))
    plt.bar(words, counts, color='lightskyblue', edgecolor='black')
    plt.title("Word Frequency Histogram (Static)", fontsize=16)
    plt.xlabel("Words", fontsize=12)
    plt.ylabel("Frequency", fontsize=12)
    plt.xticks(rotation=45)
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.savefig("Figure_1.png")
    plt.show()
    print("✅ 靜態圖已儲存為 Figure_1.png")


def plot_interactive_histogram(word_count):
    sorted_items = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
    words = [item[0] for item in sorted_items]
    counts = [item[1] for item in sorted_items]

    fig = px.bar(
        x=words,
        y=counts,
        labels={'x': 'Words', 'y': 'Frequency'},
        title="Interactive Word Frequency Histogram"
    )
    fig.update_layout(xaxis_tickangle=-45)
    fig.write_html("interactive_histogram.html")
    fig.show()
    print("✅ 互動圖已儲存為 interactive_histogram.html")


def main():
    file_path = "hw2_data.txt"

    if not os.path.exists(file_path):
        print(f"❌ 找不到檔案：{file_path}")
        return

    word_count = read_words(file_path)
    print_stats(word_count)
    plot_static_histogram(word_count)
    plot_interactive_histogram(word_count)


if __name__ == "__main__":
    main()